# Generated by Django 4.0.4 on 2022-05-05 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='size',
            field=models.IntegerField(null=True),
        ),
    ]
