# Generated by Django 4.0.4 on 2022-04-27 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productscent',
            old_name='Scent',
            new_name='scent',
        ),
    ]
