# Generated by Django 4.0.4 on 2022-04-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_scent_productscent_scent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingredient',
            new_name='skin_type',
        ),
        migrations.AddField(
            model_name='product',
            name='sense',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
