# Generated by Django 4.0.4 on 2022-05-02 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_main_description_category_sub_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='maincategory',
            new_name='main_category',
        ),
    ]
