# Generated by Django 4.0.4 on 2022-04-28 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_ingredient_skin_type_product_sense'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='skin_type',
            new_name='Ingredient',
        ),
    ]
